version: "3.9"
services:
  nginx:
    image: nginx:1.23.2
    ports:
      - 28080:80
    volumes:
      - static:/var/www/cocktail-searcher/static
    networks:
      - backend
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: ghcr.io/ampetelin/cocktail-searcher:latest
    environment:
      - DEBUG
      - SECRET_KEY=${SECRET_KEY:?error}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:?error}
      - DATABASE_URL=${DATABASE_URL:?error}
      - SENTRY_DSN
    volumes:
      - static:/opt/cocktail-searcher/static
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  nginx_config:
    file: nginx.conf

volumes:
  static:

networks:
  backend:
    name: cocktail_searcher_backend
