# Generated by Django 4.1.2 on 2022-11-09 12:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cocktail name')),
                ('image_url', models.URLField(verbose_name='Cocktail image')),
            ],
            options={
                'verbose_name': 'Cocktail',
                'verbose_name_plural': 'Cocktails',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Composition',
                'verbose_name_plural': 'Compositions',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ingredient name')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Unit name')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(verbose_name='Cooking stage')),
                ('action', models.CharField(max_length=255, verbose_name='Cooking action')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe',
                                               to='cocktails.cocktail', verbose_name='Cocktail')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='cocktails_i_name_601d45_gin'),
        ),
        migrations.AddField(
            model_name='composition',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition',
                                    to='cocktails.cocktail', verbose_name='Cocktail'),
        ),
        migrations.AddField(
            model_name='composition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient',
                                    verbose_name='Ingredient'),
        ),
        migrations.AddField(
            model_name='composition',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.unit',
                                    verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='categories',
            field=models.ManyToManyField(related_name='cocktails', to='cocktails.category',
                                         verbose_name='Cocktail categories'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('cocktail', 'stage'),
                                               name='cocktails_recipe_unique_cocktail_stage'),
        ),
        migrations.AddConstraint(
            model_name='composition',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='cocktails_composition_cpk'),
        ),
        migrations.AddIndex(
            model_name='cocktail',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='cocktails_c_name_ff7e5f_gin'),
        ),
    ]
