# Generated by Django 4.1.2 on 2022-11-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField(unique=True, verbose_name='Chat ID')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date added to favorites')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail',
                                               verbose_name='Cocktail')),
                ('telegram_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cocktails',
                                   to='telegram.telegramuser', verbose_name='Telegram user')),
            ],
            options={
                'verbose_name': 'Favorite cocktail',
                'verbose_name_plural': 'Favorite cocktails',
            },
        ),
        migrations.AddConstraint(
            model_name='favoritecocktail',
            constraint=models.UniqueConstraint(fields=('telegram_user', 'cocktail'),
                                               name='telegram_favoritecocktail_cpk'),
        ),
    ]
