name: "CD"

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: docker stack deploy -c stack.yaml ${{ github.event.repository.name }}
        env:
          DEBUG: ${{secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS}}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
